### ISSUE TITLE
Console links should load content in windows consistently

### ISSUE THREAD

**Issue by mfrances17** [integr8ly/tutorial-web-app#219]
_Originated from the UXD Team Feedback table:_
https://docs.google.com/document/d/1_AhqX8rPaZ2mfO-cI4lkhGbJLKLTWpo4HcCJ_KRhDjM/edit#heading=h.bjkplule4p3l

Console links all load into the same browser tab. From the home page, they each open their own browser tab. Can the links on the intro page behave like those on the home page?

**Comment by camilamacedo86** [comment]
Hi @mfrances17,

In this doc has too much information. If it is something that still valid could you try to improve the first comment here following up the [template](https://github.com/integr8ly/tutorial-web-app/blob/master/.github/ISSUE_TEMPLATE.md) in order to make easier the understanding? May I will be able to help with this one. ( E.g https://github.com/integr8ly/tutorial-web-app/issues/205 )

**Comment by tiffanynolan** [comment]
Migrated to JIRA to be prioritized in the backlog: https://issues.jboss.org/browse/INTLY-381
