### ISSUE TITLE
Allow the use of customized context dir for the walkthroughs

### ISSUE THREAD

**Issue by hguerrero** [integr8ly/tutorial-web-app#392]
## Description

Currently you are forced to use "walkthoughs" as the context dir for your walkthroughs (WTs) repos, when in our workshops we have only one repo with a different layout. So having a customizable CONTEX_DIR var makes sense.
## Expected Behavior

Use the CONTEXT_DIR env var to specify where to look for the WTs.
## Actual Behavior

WTs must be in "walkthroughs" dir.
## Environment
master
* Operating system: (E.g RHEL 7.6 )
* Browser and version: (E.g Google Chrome Version 70.0.3538.102 (Official Build) (64-bit))
* OpenShift version:

* Yarn version:

* Node version:

* Npm version:

* Project Version/Tag: (E.g release-1.0.1)

**Comment by evanshortiss** [comment]
This seems reasonable, but I think the PR in #393 needs some changes to work. Namely, the `WALKTHROUGH_CONTEXT_DIR` being used is applied to *all* walkthroughs.

Instead it should be mapped on a 1:1 basis so each walkthrough can have a `WALKTHROUGH_CONTEXT_DIR`. Maybe instead of using an environment variable we include an `integreatly.json` (or add an `integreatly` section into a `package.json`) in the walkthrough repository like so:

```js
{
  // We could use this as a topic/section name to create unique walkthrough groups
  "title": "My Walkthroughs",
  "description": "A set of walkthroughs that will teach you to use X",
  "walkthroughsFolder": "./custom/walkthrough-path"
}
```

Thoughts @aidenkeating @david-martin @hguerrero?

**Comment by aidenkeating** [comment]
To me, a context-dir-per-repo mapping would be the solution if we want to move away from the hard `walkthroughs/` convention. Otherwise having one repo of walkthroughs with a different structure would not allow others to be imported.

A hacky way would be to allow it to be specified in a query string of the URL or something, then just parse it out on the server. That's not very pretty though.

A concern I'd have about something like `integreatly.json` is where does it go in the repo? I'd want to be able to specify/override it, then it leads to the same issue, that's probably just me though.

I'd be happy with any context-dir-per-repo solution, or leaving it as a strict convention as I'm not sure how much time we're allocating to the webapp at the moment.

@david-martin Probably has a better insight on this though.

**Comment by evanshortiss** [comment]
@aidenkeating I'd considered querystring, but backpedalled since it could cause issues if we strip them (since we'd be using them as params) and the end user actually needed them for some reason.

Could this ever be a scenario? I don't think GitHub repos use querystring params at all, since everything is in the URL path, so maybe it's fine.

Fair point on the JSON, but I feel we'll need something like that to order the labs too, or else we order them by numbers in the ID, i.e `walkthroughs/00-lab-1`, `walkthroughs/01-lab-2`, etc.

**Comment by david-martin** [comment]
> @david-martin Probably has a better insight on this though.

Personally I think the webapp should dictate a convention rather than allow configuration for something as trivial as keeping the walkthroughs in a particularly named folder.

However, I won't push back if it's a blocker to bringing in content.
I'm happy with whatever solution works for @evanshortiss and @hguerrero here, as long as a sensible default is kept, and keeps backwards compatibility without any migration steps.

**Comment by evanshortiss** [comment]
Just investigating a little more here. The context directory can make sense if you need a monorepo setup, i.e DIL has 3 walkthrough types, but they rely on common content in that repo so they're kept together. In cases like this I understand where the context directory is helpful to avoid needing to split and maintain N repos.

> could cause issues if we strip them (since we'd be using them as webapp params) and the end user actually needed them for some reason
My above fear is not valid since Git seems to break if you attempt to include params. Querystring might be the best compromise for now. I'll take a look into this.

**Comment by catrobson** [comment]
@evanshortiss will this fix also be resolving https://github.com/integr8ly/tutorial-web-app/issues/347?

**Comment by evanshortiss** [comment]
@catrobson no, though I'd be happy to make a PR people thing it's worthwhile.

**Comment by catrobson** [comment]
@evanshortiss seems like this would help the usability quite a bit of custom walkthrough workflow.  If you have time for a PR it would be great!

**Comment by wtrocki** [comment]
@evanshortiss Awesome work!

**Comment by evanshortiss** [comment]
@wtrocki thanks! 😊

**Comment by evanshortiss** [comment]
@hguerrero or someone with admin rights, should we close this now?

**Comment by hguerrero** [comment]
@evanshortiss I saw the PR merged, but see no doc. Should we open a different issue for the documentation? Or want to reuse this one?

**Comment by evanshortiss** [comment]
@hguerrero the README covers it in [this section](https://github.com/integr8ly/tutorial-web-app#42-importing-your-external-walkthroughs-into-the-webapp).

I've created a JIRA for official documentation so we can close this and track there.

**Comment by hguerrero** [comment]
@evanshortiss there is a typo in that README as it's using 2 `?` instead of `?` and `&` for the second parameter. However, I'll close this issue as the main idea is be able to have this feature.

**Comment by evanshortiss** [comment]
@hguerrero well spotted. I opened #479 to fix it. Thanks!
